baseURL = "xrpconsultoria.netlify.com"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "XRP Consultoria"
[[menu.footer]]
name = "Contato"
url = "/contact/"
weight = 2
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Equipe"
url = "/team/"
weight = 4
[[menu.main]]
name = "Serviços"
url = "/services/"
weight = 3
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.homepage_meta_tags]
meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "XRP Consultoria"
meta_og_type = "website"
meta_og_url = "https://xrpconsultoria.netlify.com"
meta_twitter_card = "summary"
meta_twitter_creator = "@zerostaticio"
meta_twitter_site = "@zerostaticio"
[params.logo]
alt = "XRP Consultoria"
mobile = "images/logo-mobile.svg"
standard = "images/logo-xrp.svg"
